# Products Microservice properties

spring:
  application:
     name: products-service  # Service registers under this name
  freemarker:
    enabled: false           
  thymeleaf:
    cache: false            
    prefix: classpath:/products-server/templates/   # Template location for this application only

# Map the error path to error template 
error.path: /error

# HTTP Server
server.port: 2222   # HTTP (Tomcat) port

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
      # defaultZone: http://${registration.server.hostname}:1111/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 15

management.endpoints.web.exposure.include: '*'

