# Web Server Microservice properties

spring.autoconfigure.exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

spring:
  application:
    name: web-service  # Service registers under this name
  freemarker:
    enabled: false     
  thymeleaf:
    cache: false       
    prefix: classpath:/web-server/templates/     # Template location for this application

# Map the error path to error template
error.path: /error

# HTTP Server
server.port: 3333   # HTTP (Tomcat) port

eureka:
  client:
    serviceUrl:
      # defaultZone: http://localhost:1111/eureka/
     defaultZone: http://${registration.server.hostname}:1111/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 15  
    
management.endpoints.web.exposure.include: '*'